// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7CjrtSAFrxLKJLBfOy0Cl0vzCWhyQeY',
    appId: '1:980757554006:web:958538ff9695aa22a5acf7',
    messagingSenderId: '980757554006',
    projectId: 'todo-app-c3afd',
    authDomain: 'todo-app-c3afd.firebaseapp.com',
    storageBucket: 'todo-app-c3afd.firebasestorage.app',
    measurementId: 'G-B6DTWFCHHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXBn3L9-uS68TlQ1auzm4jVGAz12dylGs',
    appId: '1:980757554006:android:a18ce1a407712d05a5acf7',
    messagingSenderId: '980757554006',
    projectId: 'todo-app-c3afd',
    storageBucket: 'todo-app-c3afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzBkykKtMagSdmy9d_MPpbarnFuCObvQ',
    appId: '1:980757554006:ios:003bc9c67793e877a5acf7',
    messagingSenderId: '980757554006',
    projectId: 'todo-app-c3afd',
    storageBucket: 'todo-app-c3afd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzBkykKtMagSdmy9d_MPpbarnFuCObvQ',
    appId: '1:980757554006:ios:003bc9c67793e877a5acf7',
    messagingSenderId: '980757554006',
    projectId: 'todo-app-c3afd',
    storageBucket: 'todo-app-c3afd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp7CjrtSAFrxLKJLBfOy0Cl0vzCWhyQeY',
    appId: '1:980757554006:web:b5e573149d7bdb2fa5acf7',
    messagingSenderId: '980757554006',
    projectId: 'todo-app-c3afd',
    authDomain: 'todo-app-c3afd.firebaseapp.com',
    storageBucket: 'todo-app-c3afd.firebasestorage.app',
    measurementId: 'G-VFXYTXQG9G',
  );
}
